[package]
name = "fingertricks"
version = "0.1.0"
authors = ["jonathanloov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
